### ISSUE TITLE
Actions Workflow: May 22-23, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/assurant#1]
Add the contact info below:

- First Name/Last Name
- Business email address
- Role in customer org

**Comment by RinatS** [comment]
Rinat Shagisultanov
Technical Director
rinats@infomagnus.com

**Comment by AmerUttamchandani** [comment]
Amer Uttamchandani

AVP of DevOps Enablement 
amer.uttamchandani@assurant.com

**Comment by alpeshpatel14** [comment]
Alpesh Patel
Sr. DevOps Engineer
alpesh.patel@assurant.com

**Comment by RinatS** [comment]
Recordings

1. https://infomagnus365-my.sharepoint.com/:v:/g/personal/rinat_shagisultanov_infomagnus_com/EXHt0-zbidtBmqrkyizKHq4BQSTHfig--A5es0mfwDmLyQ?e=HWaTbe 
2. https://github.zoom.us/rec/share/Fl7XYcAu1BsRRcp5KKcIRmARAwRTvfR2_mTBllcxMIe8cnEtcH9ZY0DX8QFK1WAY.OIE1gCS6yV2kysgV
Passcode: 0+=1Qi$K
